# Generated by Django 4.2 on 2023-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodTruck",
            fields=[
                (
                    "location_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("applicant", models.CharField(max_length=255)),
                ("facility_type", models.CharField(max_length=128)),
                ("cnn", models.IntegerField()),
                ("location_description", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("block_lot", models.CharField(max_length=10)),
                ("block", models.CharField(max_length=5)),
                ("lot", models.CharField(max_length=5)),
                ("permit", models.CharField(max_length=11)),
                ("status", models.CharField(max_length=16)),
                ("food_items", models.TextField()),
                ("x", models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ("y", models.DecimalField(decimal_places=3, max_digits=16, null=True)),
                ("latitude", models.DecimalField(decimal_places=14, max_digits=16)),
                ("longitude", models.DecimalField(decimal_places=13, max_digits=16)),
                ("schedule", models.URLField(blank=True)),
                ("days_hours", models.CharField(blank=True, max_length=16)),
                ("noisent", models.CharField(blank=True, max_length=16)),
                ("approved", models.DateTimeField(null=True)),
                ("received", models.CharField(blank=True, max_length=10)),
                ("prior_permit", models.CharField(blank=True, max_length=10)),
                ("expiration_date", models.DateTimeField(null=True)),
                ("fire", models.CharField(blank=True, max_length=32)),
                ("police", models.CharField(blank=True, max_length=32)),
                ("supervisor", models.CharField(blank=True, max_length=32)),
                ("zip", models.CharField(blank=True, max_length=32)),
                ("neighborhoods", models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
